name: Deployment

"on":
  push:
    branches:
      - canary

jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1

    services:
      mongodb:
        image: mongo:4.2.6
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn Cache Directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Utilize Yarn Cache Directory
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Node_Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
      - run: yarn
        if: |
          steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Utilize Next Cache Directory
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Run App Tests
        id: app-tests
        run: yarn test

      - name: Run API Tests
        if: steps.build.app-tests == 0
        id: api-tests
        run: yarn test:api

      - name: Run E2E Tests
        if: steps.build.api-tests == 0
        id: build
        run: yarn test:e2erun
